# Generated by Django 2.2.28 on 2022-05-06 02:48

from django.db import migrations, models
import django.db.models.deletion
import parler.fields


class Migration(migrations.Migration):

    dependencies = [
        ('multilingual_events', '0002_eventagendaday_eventagendasession_eventagendatalk_eventpluginmodel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ('-start_date', '-start_time'), 'verbose_name': 'Event', 'verbose_name_plural': 'Events'},
        ),
        migrations.AlterModelOptions(
            name='eventcategorytranslation',
            options={'default_permissions': (), 'managed': True, 'verbose_name': 'Event Category Translation'},
        ),
        migrations.AlterModelOptions(
            name='eventtranslation',
            options={'default_permissions': (), 'managed': True, 'verbose_name': 'Event Translation'},
        ),
        migrations.AlterField(
            model_name='eventagendaday',
            name='cmsplugin_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='multilingual_events_eventagendaday', serialize=False, to='cms.CMSPlugin'),
        ),
        migrations.AlterField(
            model_name='eventagendasession',
            name='cmsplugin_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='multilingual_events_eventagendasession', serialize=False, to='cms.CMSPlugin'),
        ),
        migrations.AlterField(
            model_name='eventagendatalk',
            name='cmsplugin_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='multilingual_events_eventagendatalk', serialize=False, to='cms.CMSPlugin'),
        ),
        migrations.AlterField(
            model_name='eventcategorytranslation',
            name='language_code',
            field=models.CharField(db_index=True, max_length=15, verbose_name='Language'),
        ),
        migrations.AlterField(
            model_name='eventcategorytranslation',
            name='master',
            field=parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='multilingual_events.EventCategory'),
        ),
        migrations.AlterField(
            model_name='eventpluginmodel',
            name='cmsplugin_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='multilingual_events_eventpluginmodel', serialize=False, to='cms.CMSPlugin'),
        ),
        migrations.AlterField(
            model_name='eventpluginmodel',
            name='display_type',
            field=models.CharField(choices=[('small', 'small'), ('big', 'big')], max_length=256, verbose_name='Display type'),
        ),
        migrations.AlterField(
            model_name='eventtranslation',
            name='language_code',
            field=models.CharField(db_index=True, max_length=15, verbose_name='Language'),
        ),
        migrations.AlterField(
            model_name='eventtranslation',
            name='master',
            field=parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='multilingual_events.Event'),
        ),
    ]
